### ISSUE TITLE
wrong gene count

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-multi-blast#11]
<img width="898" alt="Screen Shot 2022-04-12 at 8 46 01 PM" src="https://user-images.githubusercontent.com/16354313/163458181-85a2cd88-2f05-43b4-bad9-dae9b2660fd1.png">

**Comment by jtlong3rd** [comment]
I will update the client allow custom display names (instead of the WDK record's display name, which is misleading for transcripts) in the following places:

```
1. The “Target Type” field of the result page header
2. The “XX of your YY query sequences hit ZZ things” sentence in the Combined Result tab
3. The leftmost column header in the Combined Result table
4. The “Your query sequence hit XX things” sentence in Individual Results
```
