### ISSUE TITLE
Client appears to forget or lose track of it's job status polling.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/web-multi-blast#7]
After submitting a job when on the "job running" page the client starts polling mblast every x seconds for status updates.  However, when the client leaves that page, the polling continues in the background until a full page refresh.

Additionally, if the client navigates back to that waiting page, an additional repeating poll is started, causing multiple requests to be fired every x seconds for the status.

**Comment by jtlong3rd** [comment]
To fix, the "job polling promise" should be canceled if the component which initialized it is unmounted.
