### ISSUE TITLE
Client is mis-validating POSTs to /jobs/:jobId and /reports/:reportId

### ISSUE THREAD

**Issue by jtlong3rd** [VEuPathDB/web-multi-blast#8]
The client is validating these responses with a strict `voidType` check; it should simple ignore whatever body the responses have.

**Comment by jtlong3rd** [comment]
Resolved by [this commit](https://github.com/VEuPathDB/web-multi-blast/commit/f8adc7e7f796d95d3ed05ff47e345e961370a815)

**Comment by aurreco-uga** [comment]
test: try to rerun an expired job and confirm no errors
